version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
